version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: surer
      MYSQL_USER: surer
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: surer
    ports:
      - "3305:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
